name: mediaz
channels:
  - default
  - conda-forge
dependencies:
  - ffmpeg==7.1.1
  - ffmpeg-python==0.2.0
  - pandas==2.3.0
  - pillow==11.2.1
  - pip==25.1.1
  - python==3.12.11
  - pyyaml==6.0.2
  - tqdm==4.67.1
  - pip:
      - pillow-heif==0.22.0
      - rawpy==0.25.0
